cognitivetests/cognitivetests/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls', namespace = 'user')),
    path('', include('main.urls', namespace = 'main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT)
    

cognitivetests/main/urls.py
from django.urls import path 
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.popular_list, name = 'popular_list'),
    path('shop/', views.test_list, name = 'test_list'),
    path('shop/category/<slug:category_slug>/', views.test_list, name = 'test_list_by_category'),
    path('shop/<slug:slug>/', views.test_detail,
    name = 'test_detail'),
    path('test/start/<slug:slug>/', views.test_start, name='test_start'),
]

cognitivetests/users/urls.py
from django.urls import path 
from . import views


app_name = 'users'

urlpatterns = [
    path('login/', views.login, name = 'login'),
    path('registration/', views.registration, name = 'registration'),
    path('profile/', views.profile, name = 'profile'),
    path('logout/', views.logout, name = 'logout'),
]

cognitivetests/main/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=20, unique = True)
    slug = models.SlugField(max_length = 20, unique = True)


    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['name'])]
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def get_absolute_url(self):
        return reverse('main:test_list_by_category',
                        args = [self.slug])
    
    def __str__(self):
        return self.name
        
    
class Test(models.Model):
    category = models.ForeignKey(Category,
                                related_name="tests",
                                on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50)
    image = models.ImageField(upload_to= 'tests/%Y%m%d', blank = True)
    description = models.TextField(blank = True)
    created_at = models.DateTimeField(auto_now_add=True, null = True)

    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields = ['id', 'slug']),
        models.Index(fields = ['name']),
        models.Index(fields = ['-created_at'])
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:test_detail',
                        args = [self.slug])

    
    
    
        

cognitivetests/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    image = models.ImageField(upload_to = 'users_image', blank = True, null = True)

    class Meta:
        db_table = 'user'

    def __str__(self):
        return self.username
    

cognitivetests/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from .models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField()
    password = forms.CharField()

    
    class Meta:
        model = User
        fields = ['username', 'password']

class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2',
        )
    
        first_name = forms.CharField()
        last_name = forms.CharField()
        username = forms.CharField()
        email = forms.CharField()
        password1 = forms.CharField()
        password2 = forms.CharField()

class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            'image',
            'first_name',
            'last_name',
            'username',
            'email',
        )

        image = forms.ImageField(required = False)
        first_name = forms.CharField()
        last_name = forms.CharField()
        username = forms.CharField()
        email = forms.CharField()
        
      

        

cognitivetests/main/views.py
from django.shortcuts import render, get_object_or_404
from .models import Test, Category

def popular_list(request):
    tests = Test.objects.all()
    tests = tests.order_by('-created_at')
    return render(request, 'main/index/index.html', {'tests': tests})

def test_detail(request, slug):
    test = get_object_or_404(Test, slug = slug)

    return render(request, 'main/test/detail.html', {'test' : test})

def test_list(request, category_slug = None):
    category = None
    categories = Category.objects.all()
    tests = Test.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug = category_slug)
        tests = tests.filter(category = category)
    tests = tests.order_by('-created_at')
    return render(request, 'main/test/list.html',
    {'category': category,
    'categories': categories,
    'tests': tests})

def test_start(request, slug):
    test = get_object_or_404(Test, slug=slug)
    context = {
        'test': test,
        'game_type': test.slug,  
    }
    return render(request, 'main/test/start.html', context)

cognitivetests/users/views.py
from django.shortcuts import render, redirect
from django.contrib import auth, messages
from django.urls import reverse
from django.http import HttpResponseRedirect
from .forms import UserLoginForm, UserRegistrationForm, ProfileForm
from django.contrib.auth.decorators import login_required


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data = request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username = username, password = password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('main:test_list'))
    else:
        form = UserLoginForm()
    return render(request, 'users/login.html', {'form': form})

def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data = request.POST)
        if form.is_valid():
            form.save()
            user = form.instance
            auth.login(request, user)
            messages.success(request, f'{user.username}, успешно зарегестрирован!',)
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form = UserRegistrationForm()
    return render(request, 'users/registration.html', {'form': form})



@login_required
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user, files = request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Профиль был успешно изменен!')
            return HttpResponseRedirect(reverse('user:profile'))
    else:
        form = ProfileForm(instance = request.user)

    return render(request, 'users/profile.html', {'form': form})
    


def logout(request):
    auth.logout(request)
    return redirect(reverse('main:popular_list'))

cognitivetests/main/templates/main/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>

    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">

</head>
<body>
    <header class = "header sticky-top">
        <div class = "header-container d-flex">
            <navbar class="header-nav pt-4">
                <ul class="header-list d-flex">
                    <li>
                        <a href = "/" class = "nav-a m-3">Главная</a>
                    </li>
                    <li>
                        <a href = "/shop" class = "nav-a m-3">Категории</a>
                    </li>
                </ul>    
            </navbar>
            <div class="header-logo">
                <a href="/"><img src ="{% static "image/sitelogo1.png" %}" alt ="" class="header-logo-img"></a>

                <div class="header-text">
                    <a href="/">Когнитивные тесты</a>
                </div>
            </div>
            <div class = "header-profile">
                {% if user.is_authenticated %}
                    <a href={%url "users:profile" %}>{{ user.username }}</a>
                    <a href="{% url 'users:profile' %}">
                    {% if user.image %}
                        <img src="{{ user.image.url }}"  class="header-avatar rounded-circle">
                    {% else %}
                        <img src="{% static 'image/defaultavatar.jpg' %}" class="header-avatar rounded-circle">
                    {% endif %}
                    </a>
                {% else %}
                    <a href = {%url 'users:login'%} class = "m-3">Вход</a>
                {% endif %}
                
            </div>
        </div>
    </header>
    <div class = "container">
        {% block content %}
        {% endblock content %}
    </div>
    <script src="{% static "bootstrap\js\bootstrap.bundle.min.js" %}"></script>
</body>
</html>

cognitivetests/main/templates/main/index/index.html
{% extends "main/base.html" %}
{% load static %}

{%block title%}Главная{%endblock title%}

{% block content%}
<section class="home d-flex flex-column">
    <div class="home-text mb-4">
        <h1>Добро пожаловать на главную страницу!</h1>
        <p>Здесь вы можете выбрать любой из понравившихся вам тестов.</p>
    </div>
    <div class="home-title d-flex flex-column align-items-center">
        <p class = "home-btn mt-4">ВСЕ ТЕСТЫ</p>
    </div>
    <div class="home-cards d-flex gap-4">
        {% for test in tests %}
        <a href="{{test.get_absolute_url}}" class = "home-card d-flex flex-column align-items-center text-center">
            <img src = {% if test.image %}{{test.image.url}}{%else%}{% static 'image/noimage.jpg' %}{% endif %} class ="card-img" alt="">
            <h5 class = "title-card"> {{test.name}} </h5>
        </a>
        {% endfor %}
    </div>
</section>
{% endblock content %}

cognitivetests/users/templates/users/login.html
{% extends 'main/base.html' %}
{% load static  %}

{% block title %}Вход{% endblock title %}

{% block content %}
<section class = "login d-flex">
    <div class="login-title">
        <h2>Вход</h2>
        <form action = "{% url "user:login" %}" method = "post">
            {% csrf_token %}
            {% if request.GET.next %}
                <input type = "hidden" name = "next" value = "{{request.GET.next}}">
            {% endif %}
            <div class="mb-3">
                <label for = "id_username" class = "form-label form-style" >Имя пользователя</label>
                <input type = "text" class = "form-control form-style" 
                value = "{% if form.username.value %}{{form.username.value}}{% endif %}"
                name = "username" id = "id_username" placeholder="Введите имя пользователя:" required>
            </div>
            <div class="mb-3">
                <label for = "id_password" class = "form-label form-style" >Пароль</label>
                <input type = "password" class = "form-control form-style" 
                name = "password" id = "id_password" placeholder="Введите пароль:" required>
            </div>
            <button type = "submit" class = "login-btn form-style">Войти</button>
        </form>
            <div class="reset-pass">
                <hr>
                <div class="mt-3">
                    <a href="{% url "user:registration" %}">Создать аккаунт</a> | <a href="#">Сбросить пароль</a> 
                </div>
            </div>
    </div>
</section>

{% endblock content %}

cognitivetests/users/templates/users/profile.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Профиль{% endblock title %}

{% block content %}
    <div class="d-flex">
        <div class="windowp d-flex bg-white p-4 mb-4 mx-2 rounded">
            <form action="{% url "users:profile" %}" method = "post" enctype = "multipart/form-data">
                <h2 class = "mb-2">Профиль</h2>
                {% csrf_token %}
                <div class="d-flex">
                    <div class="1box">
                        <div class="col-md-12 mb-3">
                                {% if user.image %}
                                    <img src = "{{user.image.url }}" alt = "Аватарка" class = "img-fluid" style = "max-width: 150px; max-height: 150px;">
                                {% else %}
                                    <img src = "{% static 'image/defaultavatar.jpg' %}" alt = "Аватарка" class = "img-fluid" style = "max-width: 150px; max-height: 150px;">
                                {% endif %}
                                <input type="file" class = "form-control form-styleprofile mt-2" id = "id_image" name = "image" accept = "image/*">
                        </div>
                        <div class="col-md-12 mb-3">
                            <label for="id_first_name" class = "form-label">Имя</label>
                            <input type="text" class = "form-control form-styleprofile" id = "id_first_name" name = "first_name" placeholder="Ваше имя" value = "{{form.first_name.value}}" required>
                        </div>
                        <div class="col-md-12 mb-3">
                            <label for="id_last_name" class = "form-label">Фамилия</label>
                            <input type="text" class = "form-control form-styleprofile" id = "id_last_name" name = "last_name" placeholder="Ваша фамилия" value = "{{form.last_name.value}}" required>
                        </div>
                    </div>
                        <div class="2-box">
                            <div class="col-md-12 mb-3">
                                <label for="id_username" class = "form-label">Имя пользователя</label>
                                <input type="text" class = "form-control form-styleprofile" id = "id_username" name = "username" placeholder="Ваше имя пользователя" value = "{{form.username.value}}" required> 
                        </div>
                        <div class="col-md-12 mb-3">
                                <label for="id_email" class = "form-label">Электронная почта</label>
                                <input type="email" class = "form-control form-styleprofile" id = "id_email" name = "email" placeholder="Ваша электронная почта" value = "{{form.email.value}}" required> 
                        </div>
                    </div>
                </div>
                <div class="btns d-flex gap-4 mt-4">
                    <button type = "submit" class = "profile-btn">Сохранить</button>
                    <a class = "profile-btn" href="{% url "user:logout" %}">Выйти из аккаунта</a>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

cognitivetests/users/templates/users/registration.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Регистрация{% endblock title %}

{% block content %}
    <section class = "login-reg d-flex">
        <div class="login-title">
        <h2>Регистрация</h2>
            <form action="{% url "users:registration" %}" method = "post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for = "id_first_name" class = "form-label form-stylereg">Имя</label>
                        <input type = "text" class = "form-control form-stylereg" id = "id_first_name"
                         value = "{% if form.first_name.value %}{{form.first_name.value}}{% endif %}"
                         name = "first_name" placeholder = "Ваше имя" required>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for = "id_last_name" class = "form-label form-stylereg">Фамилия</label>
                        <input type = "text" class = "form-control form-stylereg" id = "id_last_name"
                         value = "{% if form.last_name.value %}{{form.last_name.value}}{% endif %}"
                         name = "last_name" placeholder = "Ваша фамилия" required>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for = "id_username" class = "form-label form-stylereg">Имя пользователя</label>
                        <input type = "text" class = "form-control form-stylereg" id = "id_username"
                         value = "{% if form.username.value %}{{form.username.value}}{% endif %}"
                         name = "username" placeholder = "Ваше имя пользователя" required>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for = "id_email" class = "form-label form-stylereg">Электронная почта</label>
                        <input type = "email" class = "form-control form-stylereg" id = "id_email"
                         value = "{% if form.email.value %}{{form.email.value}}{% endif %}"
                         name = "email" placeholder = "Ваша электронная почта" required>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for = "id_password1" class = "form-label form-stylereg">Пароль</label>
                        <input type = "password" class = "form-control form-stylereg" id = "id_password1"
                        value = "{% if form.password1.value %}{{form.password1.value}}{% endif %}"
                         name = "password1" placeholder = "Ваш пароль" required>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for = "id_password2" class = "form-label form-stylereg">Потвердите пароль</label>
                        <input type = "password" class = "form-control form-stylereg" id = "id_password2"
                        value = "{% if form.password2.value %}{{form.password2.value}}{% endif %}"
                         name = "password2" placeholder = "Повторите пароль еще раз" required>
                    </div>
                </div>
                <button type = "submit" class = "login-btn form-style">Зарегестрироваться</button>
            </form>
        </div>
    </section>
{% endblock content %}